[package]
name = "bench-prom-decode"
version = "0.1.0"
edition = "2021"
[lib]
name = "bench_prom"
crate-type = ["lib"]

[dependencies]
greptime-proto = { git = "https://github.com/GreptimeTeam/greptime-proto", branch = "main" }
bytes = "1.5"
base64 = "0.22"
deno_core = "0.267"
prost = "0.12"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "bench_prom"
harness = false
